// Package example holds the domain model and sentinels for the example
// slice. Generated by basego as a reference vertical slice — delete or
// rename freely.
package example

// Example is the canonical domain model. Keep it pure — no tags, no infra
// types; per-driver DTOs translate to/from this at the resource boundary.
type Example struct {
	ID   string
	Name string
}
