package scaffold

import (
	"bytes"
	"embed"
	"fmt"
	"io/fs"
	"strings"
	"text/template"

	"github.com/guilherme-grimm/basego/internal/oapi"
)

//go:embed all:templates
var templatesFS embed.FS

const (
	templatesRoot = "templates"
	driversPrefix = "drivers/"
	tmplSuffix    = ".tmpl"

	// oapiCodegenVersion pins the oapi-codegen module version used in
	// `//go:generate go run ...@version` directives. Bumping here is the
	// only point of change when upgrading codegen across all generated
	// projects.
	oapiCodegenVersion = "v2.4.1"
)

// Render expands the embedded skeleton templates against req and returns a
// Plan ready for Write. The Plan's Target is req.Name; callers (or tests)
// may override it before passing to Write.
//
// Templates ending in ".tmpl" are run through text/template with req as the
// dot value. Other files are copied verbatim. The result is deterministic:
// Render builds a Plan of files from the embedded templates and any OpenAPI-derived files required by req.
// 
// It walks the embedded templates directory, maps each template path to an output path, renders files
// ending with the template suffix using req as the template data, and includes non-template files verbatim.
// Files and entire driver subtrees are skipped according to mapTemplatePath. If req.Spec is present,
// additional spec files (spec.yaml, per-tag doc.go and handler.go) are appended via specFiles.
// 
// If req is nil, Render returns an error. Any filesystem walk, read, template parse, or template execute
// error is returned with contextual file information. The returned Plan.Target is set to req.Name.
func Render(req *CreateRequest) (Plan, error) {
	if req == nil {
		return Plan{}, fmt.Errorf("scaffold: nil request")
	}
	var files []File
	err := fs.WalkDir(templatesFS, templatesRoot, func(p string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if p == templatesRoot {
			return nil
		}
		rel := strings.TrimPrefix(p, templatesRoot+"/")

		outRel, action := mapTemplatePath(req, rel, d.IsDir())
		switch action {
		case actionSkipDir:
			return fs.SkipDir
		case actionSkip:
			return nil
		}
		raw, err := templatesFS.ReadFile(p)
		if err != nil {
			return fmt.Errorf("read %s: %w", p, err)
		}
		content := raw
		if strings.HasSuffix(p, tmplSuffix) {
			t, err := template.New(outRel).Option("missingkey=error").Parse(string(raw))
			if err != nil {
				return fmt.Errorf("parse %s: %w", p, err)
			}
			var buf bytes.Buffer
			if err := t.Execute(&buf, req); err != nil {
				return fmt.Errorf("execute %s: %w", p, err)
			}
			content = buf.Bytes()
		}
		files = append(files, File{Path: outRel, Content: content})
		return nil
	})
	if err != nil {
		return Plan{}, err
	}
	files = append(files, specFiles(req)...)
	return Plan{Target: req.Name, Files: files}, nil
}

// specFiles emits the OAPI-derived files when the request carries a spec:
// the spec itself (verbatim copy) and one placeholder doc.go per tag. Real
//   - internal/api/openapi/<tag>/handler.go produced by renderHandlerGo(slice)
func specFiles(req *CreateRequest) []File {
	if req.Spec == nil {
		return nil
	}
	out := []File{{
		Path:    "internal/api/openapi/spec.yaml",
		Content: req.SpecBytes,
	}}
	for _, s := range req.Spec.Slices {
		out = append(out,
			File{
				Path:    "internal/api/openapi/" + s.Tag + "/doc.go",
				Content: []byte(renderDocGo(s.Tag)),
			},
			File{
				Path:    "internal/api/openapi/" + s.Tag + "/handler.go",
				Content: []byte(renderHandlerGo(s)),
			},
		)
	}
	return out
}

// handlerTemplate is the body of each slice's handler.go. CRUD-detected
// operations get a 501-returning placeholder so the route is reachable but
// unimplemented; non-CRUD operations panic so accidental routing through
// an unfinished custom verb surfaces loudly (DESIGN §5).
const handlerTemplate = `// Package {{.Tag}} hosts the HTTP handlers for the {{.Tag}} slice.
// Generated by basego from the OpenAPI spec; safe to extend by hand.
package {{.Tag}}

import "net/http"

// Handler implements the {{.Tag}} slice's HTTP routes. Constructed once at
// startup and wired into the router; each method below corresponds to a
// spec operation.
type Handler struct{}

func NewHandler() *Handler { return &Handler{} }
{{range .Operations}}
// {{.MethodName}} — {{.Method}} {{.Path}}{{if .CRUD}} (CRUD: {{.CRUD}}){{else}} (non-CRUD){{end}}.
func (h *Handler) {{.MethodName}}(w http.ResponseWriter, _ *http.Request) {
{{- if .CRUD }}
	// TODO: wire to gateway once types_gen.go is generated.
	w.WriteHeader(http.StatusNotImplemented)
{{- else }}
	panic("{{$.Tag}}.Handler.{{.MethodName}}: not implemented")
{{- end }}
}
{{end}}`

// renderHandlerGo renders the handler.go source for the given OpenAPI slice.
// It returns the generated Go source as a string. If template execution fails
// (which is treated as a programmer error because the template is constant and
// the input is expected to be well-formed), the function panics with an
// explanatory message.
func renderHandlerGo(slice oapi.Slice) string {
	t := template.Must(template.New("handler").Parse(handlerTemplate))
	var buf bytes.Buffer
	if err := t.Execute(&buf, slice); err != nil {
		// Template is constant + slice is well-formed; an error here is
		// a programmer mistake, not a runtime condition.
		panic(fmt.Sprintf("scaffold: render handler.go for %q: %v", slice.Tag, err))
	}
	return buf.String()
}

// renderDocGo builds the per-slice doc.go body. It contains the package
// declaration plus a //go:generate directive that invokes oapi-codegen on
// demand via `go run pkg@version` — no tool dep is added to the generated
// project's go.mod, so projects compile offline and only need network when
// renderDocGo returns the source text for a package-level doc.go for the named slice.
// The generated doc.go declares package <tag>, documents how to regenerate generated
// types, and embeds a //go:generate directive that invokes oapi-codegen pinned to
// the scaffold's configured version to produce `types_gen.go` for the given tag from ../spec.yaml.
func renderDocGo(tag string) string {
	return "// Package " + tag + " holds the generated OpenAPI types and (in a\n" +
		"// follow-up deliverable) server stubs for the " + tag + " slice.\n" +
		"//\n" +
		"// Run `make generate` (or `go generate ./...`) to (re-)generate\n" +
		"// types_gen.go from the spec.\n" +
		"package " + tag + "\n" +
		"\n" +
		"//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@" + oapiCodegenVersion +
		" -package=" + tag + " -generate=types -include-tags=" + tag +
		" -o=types_gen.go ../spec.yaml\n"
}

type pathAction int

const (
	actionEmit    pathAction = iota // emit a file with the returned outRel
	actionSkip                      // skip this entry (e.g. directory, unselected driver file)
	actionSkipDir                   // skip the whole subtree (unselected driver dir)
)

// mapTemplatePath resolves an embed-relative path to its output path and
// decides whether to render it. Files under drivers/<name>/ are only
// rendered when req.HasDriver(name); the drivers/<name>/ prefix is then
// stripped from the output.
func mapTemplatePath(req *CreateRequest, rel string, isDir bool) (string, pathAction) {
	if rel == "drivers" {
		return "", actionSkip
	}
	if strings.HasPrefix(rel, driversPrefix) {
		sub := strings.TrimPrefix(rel, driversPrefix)
		driver, inner, _ := splitOnce(sub, "/")
		if !req.HasDriver(driver) {
			if isDir {
				return "", actionSkipDir
			}
			return "", actionSkip
		}
		if isDir || inner == "" {
			return "", actionSkip
		}
		return strings.TrimSuffix(inner, tmplSuffix), actionEmit
	}
	if isDir {
		return "", actionSkip
	}
	return strings.TrimSuffix(rel, tmplSuffix), actionEmit
}

func splitOnce(s, sep string) (head, tail string, ok bool) {
	i := strings.Index(s, sep)
	if i < 0 {
		return s, "", false
	}
	return s[:i], s[i+len(sep):], true
}
